### ISSUE TITLE
'user id' undefined

### ISSUE THREAD

**Issue by Loyelnaz** [BDFP/jivox-hack-store#1]
The 'user id' stored in the local storage is undefined throughout. The user gets logged in successfully but it gives undesirable output while 'user id' comes into the picture. In the case of the recommendation for a particular user, it considers 'user id' of the first user and gives recommendations irrespective of the user being logged in.

**Comment by shreyans4nahata** [comment]
Can you check whether the angularJs factory defined for account login and signup is hitting the correct api. Also print the api call you are making, that could give an in depth overview of the problem.
